/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type TransactionLog = {};

export type ActiveBanksList = {};

export type BankDistribution = {};

export type SettlementOverview = {};

export type MondayClearingPreparation = {};

/**
 * Dashboard metrics
 */
export type GetDashboardMetricsResponse = {
  activeBanks?: number | undefined;
  totalRevenue?: number | undefined;
  completionRate?: number | undefined;
  revenueOverview?: Array<number> | undefined;
  transactionLogs?: Array<TransactionLog> | undefined;
  activeBanksList?: Array<ActiveBanksList> | undefined;
  bankDistributions?: Array<BankDistribution> | undefined;
  activeTransactions?: Array<models.Transaction> | undefined;
  settlementOverview?: SettlementOverview | undefined;
  mondayClearingPreparation?: MondayClearingPreparation | undefined;
};

/** @internal */
export const TransactionLog$inboundSchema: z.ZodMiniType<
  TransactionLog,
  unknown
> = z.object({});

export function transactionLogFromJSON(
  jsonString: string,
): SafeParseResult<TransactionLog, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionLog$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionLog' from JSON`,
  );
}

/** @internal */
export const ActiveBanksList$inboundSchema: z.ZodMiniType<
  ActiveBanksList,
  unknown
> = z.object({});

export function activeBanksListFromJSON(
  jsonString: string,
): SafeParseResult<ActiveBanksList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActiveBanksList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActiveBanksList' from JSON`,
  );
}

/** @internal */
export const BankDistribution$inboundSchema: z.ZodMiniType<
  BankDistribution,
  unknown
> = z.object({});

export function bankDistributionFromJSON(
  jsonString: string,
): SafeParseResult<BankDistribution, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BankDistribution$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BankDistribution' from JSON`,
  );
}

/** @internal */
export const SettlementOverview$inboundSchema: z.ZodMiniType<
  SettlementOverview,
  unknown
> = z.object({});

export function settlementOverviewFromJSON(
  jsonString: string,
): SafeParseResult<SettlementOverview, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SettlementOverview$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SettlementOverview' from JSON`,
  );
}

/** @internal */
export const MondayClearingPreparation$inboundSchema: z.ZodMiniType<
  MondayClearingPreparation,
  unknown
> = z.object({});

export function mondayClearingPreparationFromJSON(
  jsonString: string,
): SafeParseResult<MondayClearingPreparation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MondayClearingPreparation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MondayClearingPreparation' from JSON`,
  );
}

/** @internal */
export const GetDashboardMetricsResponse$inboundSchema: z.ZodMiniType<
  GetDashboardMetricsResponse,
  unknown
> = z.object({
  activeBanks: types.optional(types.number()),
  totalRevenue: types.optional(types.number()),
  completionRate: types.optional(types.number()),
  revenueOverview: types.optional(z.array(types.number())),
  transactionLogs: types.optional(
    z.array(z.lazy(() => TransactionLog$inboundSchema)),
  ),
  activeBanksList: types.optional(
    z.array(z.lazy(() => ActiveBanksList$inboundSchema)),
  ),
  bankDistributions: types.optional(
    z.array(z.lazy(() => BankDistribution$inboundSchema)),
  ),
  activeTransactions: types.optional(z.array(models.Transaction$inboundSchema)),
  settlementOverview: types.optional(
    z.lazy(() => SettlementOverview$inboundSchema),
  ),
  mondayClearingPreparation: types.optional(
    z.lazy(() => MondayClearingPreparation$inboundSchema),
  ),
});

export function getDashboardMetricsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetDashboardMetricsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDashboardMetricsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDashboardMetricsResponse' from JSON`,
  );
}
