/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Health status
 */
export type GetHealthResponse = {
  status?: string | undefined;
  timestamp?: Date | undefined;
};

/** @internal */
export const GetHealthResponse$inboundSchema: z.ZodMiniType<
  GetHealthResponse,
  unknown
> = z.object({
  status: types.optional(types.string()),
  timestamp: types.optional(types.date()),
});

export function getHealthResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetHealthResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetHealthResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHealthResponse' from JSON`,
  );
}
