/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * List of pending transactions
 */
export type GetLedgerPendingResponse = {
  pending?: Array<models.Transaction> | undefined;
};

/** @internal */
export const GetLedgerPendingResponse$inboundSchema: z.ZodMiniType<
  GetLedgerPendingResponse,
  unknown
> = z.object({
  pending: types.optional(z.array(models.Transaction$inboundSchema)),
});

export function getLedgerPendingResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetLedgerPendingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLedgerPendingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLedgerPendingResponse' from JSON`,
  );
}
