/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetTransactionsRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
};

export type Pagination = {
  page?: number | undefined;
  pageSize?: number | undefined;
  totalPages?: number | undefined;
};

/**
 * Transactions and summary
 */
export type GetTransactionsResponse = {
  transactions?: Array<models.Transaction> | undefined;
  pagination?: Pagination | undefined;
};

/** @internal */
export type GetTransactionsRequest$Outbound = {
  page?: number | undefined;
  pageSize?: number | undefined;
};

/** @internal */
export const GetTransactionsRequest$outboundSchema: z.ZodMiniType<
  GetTransactionsRequest$Outbound,
  GetTransactionsRequest
> = z.object({
  page: z.optional(z.int()),
  pageSize: z.optional(z.int()),
});

export function getTransactionsRequestToJSON(
  getTransactionsRequest: GetTransactionsRequest,
): string {
  return JSON.stringify(
    GetTransactionsRequest$outboundSchema.parse(getTransactionsRequest),
  );
}

/** @internal */
export const Pagination$inboundSchema: z.ZodMiniType<Pagination, unknown> = z
  .object({
    page: types.optional(types.number()),
    pageSize: types.optional(types.number()),
    totalPages: types.optional(types.number()),
  });

export function paginationFromJSON(
  jsonString: string,
): SafeParseResult<Pagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pagination' from JSON`,
  );
}

/** @internal */
export const GetTransactionsResponse$inboundSchema: z.ZodMiniType<
  GetTransactionsResponse,
  unknown
> = z.object({
  transactions: types.optional(z.array(models.Transaction$inboundSchema)),
  pagination: types.optional(z.lazy(() => Pagination$inboundSchema)),
});

export function getTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionsResponse' from JSON`,
  );
}
