/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostSimulatorStartRequest = {
  count?: number | undefined;
  interval?: number | undefined;
};

/**
 * Simulation started
 */
export type PostSimulatorStartResponse = {
  message?: string | undefined;
};

/** @internal */
export type PostSimulatorStartRequest$Outbound = {
  count: number;
  interval: number;
};

/** @internal */
export const PostSimulatorStartRequest$outboundSchema: z.ZodMiniType<
  PostSimulatorStartRequest$Outbound,
  PostSimulatorStartRequest
> = z.object({
  count: z._default(z.int(), 10),
  interval: z._default(z.int(), 1000),
});

export function postSimulatorStartRequestToJSON(
  postSimulatorStartRequest: PostSimulatorStartRequest,
): string {
  return JSON.stringify(
    PostSimulatorStartRequest$outboundSchema.parse(postSimulatorStartRequest),
  );
}

/** @internal */
export const PostSimulatorStartResponse$inboundSchema: z.ZodMiniType<
  PostSimulatorStartResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function postSimulatorStartResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostSimulatorStartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostSimulatorStartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostSimulatorStartResponse' from JSON`,
  );
}
