/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Settlement complete
 */
export type PostLedgerSettleResponse = {
  message?: string | undefined;
  settled?: Array<models.Transaction> | undefined;
};

/** @internal */
export const PostLedgerSettleResponse$inboundSchema: z.ZodMiniType<
  PostLedgerSettleResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  settled: types.optional(z.array(models.Transaction$inboundSchema)),
});

export function postLedgerSettleResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostLedgerSettleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostLedgerSettleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostLedgerSettleResponse' from JSON`,
  );
}
