/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Transaction received
 */
export type PostWebhookResponse = {
  message?: string | undefined;
  txnRef?: string | undefined;
};

/** @internal */
export const PostWebhookResponse$inboundSchema: z.ZodMiniType<
  PostWebhookResponse,
  unknown
> = z.pipe(
  z.object({
    message: types.optional(types.string()),
    txn_ref: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "txn_ref": "txnRef",
    });
  }),
);

export function postWebhookResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostWebhookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostWebhookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostWebhookResponse' from JSON`,
  );
}
