/**
 * Rails TypeScript SDK
 * 
 * This file will be auto-generated by Speakeasy.
 * For now, it serves as a placeholder.
 * 
 * Once you run Speakeasy generation, this file will contain:
 * - Main SDK class
 * - All endpoint methods
 * - Type definitions
 * - Error handling
 */

export * from './sdk';
export * from './types';
