/**
 * Rails SDK - Main SDK Class
 * 
 * This will be auto-generated by Speakeasy.
 * Placeholder for now.
 */

export class RailsSDK {
  constructor(config: {
    apiKey?: string;
    accessToken?: string;
    baseURL?: string;
    timeout?: number;
    retries?: number;
    debug?: boolean;
  }) {
    // Placeholder - will be generated by Speakeasy
  }
}
