/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the cmos SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx postWebhook.example.ts
 */

import { Cmos } from "cmos";

const cmos = new Cmos();

async function main() {
  const result = await cmos.postWebhook({});

  console.log(result);
}

main().catch(console.error);
