# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ledger.proto for package 'rails.ledger.v1'

require 'grpc'
require_relative 'ledger_pb'

module Rails
  module Ledger
    module V1
      module LedgerService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'rails.ledger.v1.LedgerService'

          rpc :PostTransaction, ::Rails::Ledger::V1::PostTransactionRequest, ::Rails::Ledger::V1::PostTransactionResponse
          rpc :GetAccountBalance, ::Rails::Ledger::V1::GetAccountBalanceRequest, ::Rails::Ledger::V1::GetAccountBalanceResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
