# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ledger.proto

require 'google/protobuf'


descriptor_data = "\n\x0cledger.proto\x12\x0frails.ledger.v1\"\xa5\x02\n\x16PostTransactionRequest\x12\x17\n\x0forganization_id\x18\x01 \x01(\t\x12\x31\n\x0b\x65nvironment\x18\x02 \x01(\x0e\x32\x1c.rails.ledger.v1.Environment\x12\"\n\x1asource_external_account_id\x18\x03 \x01(\t\x12\'\n\x1f\x64\x65stination_external_account_id\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x06 \x01(\t\x12\x1f\n\x17\x65xternal_transaction_id\x18\x07 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x08 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\t \x01(\t\"`\n\x17PostTransactionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1d\n\x15ledger_transaction_id\x18\x02 \x01(\t\x12\x16\n\x0e\x66\x61ilure_reason\x18\x03 \x01(\t\"\x95\x01\n\x18GetAccountBalanceRequest\x12\x17\n\x0forganization_id\x18\x01 \x01(\t\x12\x31\n\x0b\x65nvironment\x18\x02 \x01(\x0e\x32\x1c.rails.ledger.v1.Environment\x12\x1b\n\x13\x65xternal_account_id\x18\x03 \x01(\t\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\">\n\x19GetAccountBalanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\t\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t*G\n\x0b\x45nvironment\x12\x1b\n\x17\x45NVIRONMENT_UNSPECIFIED\x10\x00\x12\x0b\n\x07SANDBOX\x10\x01\x12\x0e\n\nPRODUCTION\x10\x02\x32\xe1\x01\n\rLedgerService\x12\x64\n\x0fPostTransaction\x12\'.rails.ledger.v1.PostTransactionRequest\x1a(.rails.ledger.v1.PostTransactionResponse\x12j\n\x11GetAccountBalance\x12).rails.ledger.v1.GetAccountBalanceRequest\x1a*.rails.ledger.v1.GetAccountBalanceResponseB$\n\x13\x63om.rails.ledger.v1B\x0bLedgerProtoP\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Rails
  module Ledger
    module V1
      PostTransactionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rails.ledger.v1.PostTransactionRequest").msgclass
      PostTransactionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rails.ledger.v1.PostTransactionResponse").msgclass
      GetAccountBalanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rails.ledger.v1.GetAccountBalanceRequest").msgclass
      GetAccountBalanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rails.ledger.v1.GetAccountBalanceResponse").msgclass
      Environment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rails.ledger.v1.Environment").enummodule
    end
  end
end
