/**
 * TypeScript Type Definitions
 * 
 * These will be auto-generated by Speakeasy based on your OpenAPI spec.
 * Placeholder for now.
 */

export interface Transaction {
  txn_ref: string;
  sender_account: string;
  receiver_account: string;
  sender_bank: string;
  receiver_bank: string;
  amount: number;
  currency: string;
  timestamp: string;
  metadata?: Record<string, any>;
  status?: string;
  settled?: boolean;
}

export interface Error {
  error: string;
  message: string;
  details?: any;
  correlation_id?: string;
  timestamp?: string;
}
